### ISSUE TITLE
Create site pages

### ISSUE THREAD

**Issue by carter-bardellmunro** [matai-2021/music-dating-app#10]
- [x]  Create login/register page
- [x]  Create profile page
- [x]  Create swipe page
- [x]  Create chat page

**Comment by carter-bardellmunro** [comment]
- [x] Create login/register page
- [ ] Create profile page 
- [x] Create swipe page
- [ ] Create chat page

**Comment by dylan-toomey** [comment]
Create login/register page, Working on this not done.

>> Done Now

**Comment by dylan-toomey** [comment]
Starting to work on react tinder component to create swipe page.

**Comment by dylan-toomey** [comment]
Profile page is created just need to manage the edit part.
